### PR TITLE
Move base image from ubuntu:18.04 to debian:12

### PR DESCRIPTION
**Pull request by chrfranke**
This _somewhat_ updates our CI build environment.

Builds were tested locally with all recipes from smartmontools `trunk/.circleci/config.yml`.

**Important**: The Darwin and FreeBSD builds were not actually tested yet on a real machine. Linux and Windows builds work.

The FreeBSD builds require this patch which reverts to the default `clang` and fixes the C++ system include path:
```patch
Index: trunk/.circleci/config.yml
===================================================================
--- trunk/.circleci/config.yml	(revision 5488)
+++ trunk/.circleci/config.yml	(working copy)
@@ -138,7 +138,9 @@
         tar -xzf /artefacts/smartmontools-${SM_VER}-r${SVNREV}.src.tar.gz &&
         cd smartmontools-${SM_VER} && mkdir build && cd build &&
         TARGET="-target x86_64-unknown-freebsd13 --sysroot=/opt/cross-freebsd-13/" &&
-        ../configure CC="clang-10 $TARGET" CXX="clang++-10 $TARGET" LDFLAGS="-static" --host=x86_64-pc-freebsd13 &&
+        ../configure CC="clang $TARGET" CXX="clang++ $TARGET" \
+          CPPFLAGS="-isystem /opt/cross-freebsd-13/usr/include/c++/v1" \
+          LDFLAGS="-static" --host=x86_64-pc-freebsd13 &&
         make -j2 BUILD_INFO="$BUILD_INFO" &&
         mkdir inst && make DESTDIR="$(pwd)/inst" install &&
         (cd inst && tar czf "/artefacts/smartmontools-freebsd13.2-amd64-static-${SM_VER}-r${SVNREV}.tar.gz" *) &&
@@ -154,7 +156,9 @@
         tar -xzf /artefacts/smartmontools-${SM_VER}-r${SVNREV}.src.tar.gz &&
         cd smartmontools-${SM_VER} && mkdir build && cd build &&
         TARGET="-target x86_64-unknown-freebsd12 --sysroot=/opt/cross-freebsd-12/" &&
-        ../configure CC="clang $TARGET" CXX="clang++ $TARGET" LDFLAGS="-static" --host=x86_64-pc-freebsd12 &&
+        ../configure CC="clang $TARGET" CXX="clang++ $TARGET" \
+          CPPFLAGS="-isystem /opt/cross-freebsd-12/usr/include/c++/v1" \
+          LDFLAGS="-static" --host=x86_64-pc-freebsd12 &&
         make -j2 BUILD_INFO="$BUILD_INFO" &&
         mkdir inst && make DESTDIR="$(pwd)/inst" install &&
         (cd inst && tar czf "/artefacts/smartmontools-freebsd12.4-amd64-static-${SM_VER}-r${SVNREV}.tar.gz" *) &&
```

### CODE REVIEW

**Comment by samm-git** [comment]
Looks good, thank you! I did a quick test for the darwin, seems to work. Will test more after merging on CI builds

**Comment by chrfranke** [comment]
A re-run of builds at [CircleCI](https://app.circleci.com/pipelines/github/smartmontools/smartmontools) failed at FreeBSD step as expected. Now fixed with [r5490](https://www.smartmontools.org/changeset/5490).

**Comment by chrfranke** [comment]
A quick test of the r5490 FreeBSD-13 CI build looks good. I used the VHD image from https://download.freebsd.org/releases/VM-IMAGES/13.2-RELEASE/amd64/Latest/ in VirtualBox and a real SATA SSD attached via a SAT capable USB docking station.

**Comment by samm-git** [comment]
tested darwin build on macos 11.7.8, x86_64, works fime. Also i see that multi-binary was built correctly:

```
bash-3.2$ file /usr/local/sbin/smartctl
/usr/local/sbin/smartctl: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64]
/usr/local/sbin/smartctl (for architecture x86_64):	Mach-O 64-bit executable x86_64
/usr/local/sbin/smartctl (for architecture arm64):	Mach-O 64-bit executable arm64
```

Test on FreeBSD 13.2 also show no errors, so we are fine. 

```
srvadm@fbsd:~ % file usr/local/sbin/smartctl
usr/local/sbin/smartctl: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for FreeBSD 13.2, FreeBSD-style, with debug_info, not stripped
```

**Pull request merged**
